repository: corona-warn-app/cwa-verification-server
current_version: "null"
rules:
  - org.palladiosimulator.retriever.extraction.rules.maven
  - org.palladiosimulator.retriever.extraction.rules.spring
