repository: georgwittberger/apache-spring-boot-microservice-example
current_version: "null"
rules:
  - org.palladiosimulator.retriever.extraction.rules.maven
  - org.palladiosimulator.retriever.extraction.rules.spring
