repository: kbastani/spring-cloud-event-sourcing-example
current_version: "null"
rules:
  - org.palladiosimulator.retriever.extraction.rules.maven
  - org.palladiosimulator.retriever.extraction.rules.spring
