repository: yidongnan/spring-cloud-netflix-example
current_version: "null"
rules:
  - org.palladiosimulator.retriever.extraction.rules.gradle
  - org.palladiosimulator.retriever.extraction.rules.spring
