repository:
  - openmrs/openmrs-core
  - openmrs/openmrs-module-webservices.rest
current_version: v5.2.0.202404160757
rules:
  - org.palladiosimulator.retriever.extraction.rules.maven
  - org.palladiosimulator.retriever.extraction.rules.spring
